# Generated by Django 4.2.3 on 2023-07-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='column',
            field=models.IntegerField(default=1, verbose_name='столбец'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='row',
            field=models.IntegerField(default=1, verbose_name='ряд'),
            preserve_default=False,
        ),
    ]
