# Generated by Django 4.2.3 on 2023-07-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contact_column_contact_row'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='foreground_color',
            field=models.TextField(default='lightcyan', max_length=255, verbose_name='цвет'),
        ),
    ]
