# Generated by Django 4.2.3 on 2023-08-16 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_block_alter_contact_options_remove_contact_column_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='описание'),
        ),
    ]
