# Generated by Django 4.2.3 on 2023-08-20 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_block_options_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(upload_to='', verbose_name='background-image')),
                ('logo', models.ImageField(upload_to='', verbose_name='logo')),
                ('title', models.TextField(blank=True, max_length=255, verbose_name='title')),
                ('name', models.TextField(blank=True, max_length=255, verbose_name='name')),
                ('description_json_array', models.TextField(blank=True, verbose_name='description-json-array')),
            ],
            options={
                'verbose_name': 'settings',
                'verbose_name_plural': 'settings',
            },
        ),
    ]
