# Generated by Django 4.2.3 on 2023-08-20 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='logo',
        ),
        migrations.AddField(
            model_name='settings',
            name='icon',
            field=models.ImageField(null=True, upload_to='', verbose_name='icon'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='background_image',
            field=models.ImageField(null=True, upload_to='', verbose_name='background-image'),
        ),
    ]
