# Generated by Django 4.2.3 on 2023-08-21 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_settings_background_image_alter_settings_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='description_json_array',
        ),
        migrations.AddField(
            model_name='settings',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
    ]
