# Generated by Django 4.2.3 on 2023-09-08 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_settings_description_json_array_and_more'),
    ]

    operations = [
        migrations.RenameModel('Settings', 'Page')
    ]
