# Generated by Django 4.2.3 on 2023-09-08 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_block_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='block', related_query_name='blocks', to='main.page', verbose_name='page'),
        ),
    ]
