# Generated by Django 4.2.3 on 2023-09-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_block_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.SlugField(default='homepage', max_length=255, unique=True, verbose_name='slug'),
            preserve_default=False,
        ),
    ]
