# Generated by Django 4.2.3 on 2023-09-08 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_page_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['order_id'], 'verbose_name': 'item', 'verbose_name_plural': 'items'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='row',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', related_query_name='item', to='main.row', verbose_name='row'),
        ),
    ]
