# Generated by Django 4.2.3 on 2023-07-21 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='заголовок')),
                ('url', models.TextField(verbose_name='ссылка')),
                ('icon', models.ImageField(upload_to='', verbose_name='иконка')),
                ('background', models.ImageField(upload_to='', verbose_name='задний фон')),
                ('is_visible', models.BooleanField(default=True, verbose_name='отображать?')),
            ],
            options={
                'verbose_name': 'контакт',
                'verbose_name_plural': 'контакты',
            },
        ),
    ]
