# Generated by Django 4.2.3 on 2023-08-20 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_block_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'ordering': ['order_id'], 'verbose_name': 'block', 'verbose_name_plural': 'blocks'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['order_id'], 'verbose_name': 'contact', 'verbose_name_plural': 'contacts'},
        ),
        migrations.AlterModelOptions(
            name='row',
            options={'ordering': ['order_id'], 'verbose_name': 'row', 'verbose_name_plural': 'rows'},
        ),
        migrations.RemoveField(
            model_name='contact',
            name='background',
        ),
        migrations.AddField(
            model_name='contact',
            name='background_color',
            field=models.TextField(default='midnightblue', max_length=255, verbose_name='background-color'),
        ),
        migrations.AlterField(
            model_name='block',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='block',
            name='order_id',
            field=models.IntegerField(verbose_name='order-id'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='foreground_color',
            field=models.TextField(default='lightcyan', max_length=255, verbose_name='foreground-color'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='icon',
            field=models.ImageField(upload_to='', verbose_name='icon'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='order_id',
            field=models.IntegerField(verbose_name='order_id'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='row',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', related_query_name='contact', to='main.row', verbose_name='row'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='title',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='url',
            field=models.TextField(verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='row',
            name='block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rows', related_query_name='row', to='main.block', verbose_name='block'),
        ),
        migrations.AlterField(
            model_name='row',
            name='order_id',
            field=models.IntegerField(verbose_name='order-id'),
        ),
    ]
